#!/usr/bin/env python3
"""Post-freeze expected-finding data for the spent fresh contest holdouts.

The data in this module is answer-key material. It is only for scoring frozen
outputs after detection artifacts have been hashed. Do not import this module
from detector/source-to-lead code.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

PUBLIC_ROOT = Path(__file__).resolve().parents[1] / "benchmarks" / "public-historical-corpus"


FRESH_EXPECTED: dict[str, list[dict[str, Any]]] = {
    "contest_2001": [
        {"finding_id": "H-01", "title": "WellUpgradeable can be upgraded by anyone", "expected_severity": "High", "root_cause": "missing upgrade authorization", "bug_class": "access-control", "source_file": "src/WellUpgradeable.sol", "affected_contract": "WellUpgradeable", "affected_function": "_authorizeUpgrade", "affected_asset": "well implementations and funds controlled by upgraded wells", "impact_type": "unauthorized-privileged-action"},
        {"finding_id": "H-02", "title": "Incorrectly assigned decimal1 parameter upon decoding", "expected_severity": "High", "root_cause": "wrong variable checked when normalizing token1 decimals", "bug_class": "decimal-accounting", "source_file": "src/functions/Stable2.sol", "affected_contract": "Stable2", "affected_function": "decodeWellData", "affected_asset": "AMM reserves and price calculations", "impact_type": "stolen-funds-or-bad-pricing"},
        {"finding_id": "M-01", "title": "For extreme ratios getRatiosFromPriceSwap returns data impossible to converge into a reserve", "expected_severity": "Medium", "root_cause": "lookup table extreme price range step size breaks convergence", "bug_class": "math-convergence", "source_file": "src/functions/StableLUT/Stable2LUT1.sol", "affected_contract": "Stable2LUT1", "affected_function": "getRatiosFromPriceSwap", "affected_asset": "AMM reserve calculation availability", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-02", "title": "Stable2LUT1 getRatiosFromPriceLiquidity extreme cases break updateReserve", "expected_severity": "Medium", "root_cause": "lookup table extreme liquidity price range step size underflows or fails convergence", "bug_class": "math-convergence", "source_file": "src/functions/StableLUT/Stable2LUT1.sol", "affected_contract": "Stable2LUT1", "affected_function": "getRatiosFromPriceLiquidity", "affected_asset": "AMM reserve calculation availability", "impact_type": "frozen-funds-or-availability"},
    ],
    "contest_2002": [
        {"finding_id": "H-01", "title": "SettleLongPremium is incorrectly implemented: premium should be deducted instead of added", "expected_severity": "High", "root_cause": "premium sign is inverted when settling long premium", "bug_class": "accounting-desync", "source_file": "contracts/PanopticPool.sol", "affected_contract": "PanopticPool", "affected_function": "settleLongPremium", "affected_asset": "collateral tracker balances", "impact_type": "stolen-funds"},
        {"finding_id": "H-02", "title": "Overflow in CollateralTracker allows minting shares for free", "expected_severity": "High", "root_cause": "unchecked multiplication in previewMint overflows", "bug_class": "overflow", "source_file": "contracts/CollateralTracker.sol", "affected_contract": "CollateralTracker", "affected_function": "mint", "affected_asset": "collateral shares", "impact_type": "stolen-funds"},
        {"finding_id": "M-01", "title": "PanopticFactory uses spot price when deploying new pools", "expected_severity": "Medium", "root_cause": "spot price used without manipulation protection", "bug_class": "oracle-manipulation", "source_file": "contracts/PanopticFactory.sol", "affected_contract": "PanopticFactory", "affected_function": "_mintFullRange", "affected_asset": "pool deployer token balances", "impact_type": "stolen-funds"},
        {"finding_id": "M-02", "title": "_validatePositionList does not check for duplicate tokenIds", "expected_severity": "Medium", "root_cause": "position hash allows duplicate token IDs to bypass solvency checks", "bug_class": "invalid-validation", "source_file": "contracts/PanopticPool.sol", "affected_contract": "PanopticPool", "affected_function": "_validatePositionList", "affected_asset": "collateral and solvency accounting", "impact_type": "bad-debt"},
        {"finding_id": "M-03", "title": "CREATE2 address collision during pool deployment allows complete draining of the pool", "expected_severity": "Medium", "root_cause": "pool deployment address can collide with predeployed contract", "bug_class": "create2-collision", "source_file": "contracts/SemiFungiblePositionManager.sol", "affected_contract": "SemiFungiblePositionManager", "affected_function": "initializeAMMPool", "affected_asset": "pool assets", "impact_type": "stolen-funds"},
        {"finding_id": "M-04", "title": "Incorrect validation during checking liquidity spread", "expected_severity": "Medium", "root_cause": "liquidity spread validation accepts invalid position shape", "bug_class": "invalid-validation", "source_file": "contracts/SemiFungiblePositionManager.sol", "affected_contract": "SemiFungiblePositionManager", "affected_function": "_validateAndForwardToAMM", "affected_asset": "option position liquidity", "impact_type": "bad-debt"},
        {"finding_id": "M-05", "title": "Panoptic pool can be non-profitable by specific Uniswap governance", "expected_severity": "Medium", "root_cause": "external Uniswap fee configuration can make pool economics invalid", "bug_class": "external-dependency", "source_file": "contracts/PanopticPool.sol", "affected_contract": "PanopticPool", "affected_function": "startPool", "affected_asset": "pool profitability", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-06", "title": "_updateSettlementPostBurn may not correctly reduce s_grossPremiumLast", "expected_severity": "Medium", "root_cause": "post-burn settlement premium accumulator can be reduced incorrectly", "bug_class": "accounting-desync", "source_file": "contracts/PanopticPool.sol", "affected_contract": "PanopticPool", "affected_function": "_updateSettlementPostBurn", "affected_asset": "premium accounting", "impact_type": "stolen-funds"},
        {"finding_id": "M-07", "title": "Burning a tokenized position validates after flipping isLong bits", "expected_severity": "Medium", "root_cause": "validation order uses mutated tokenId state", "bug_class": "invalid-validation", "source_file": "contracts/SemiFungiblePositionManager.sol", "affected_contract": "SemiFungiblePositionManager", "affected_function": "_validateAndForwardToAMM", "affected_asset": "option position accounting", "impact_type": "bad-debt"},
        {"finding_id": "M-08", "title": "Wrong leg chunkKey calculation in haircutPremia", "expected_severity": "Medium", "root_cause": "wrong chunk key used for premium haircut", "bug_class": "accounting-desync", "source_file": "contracts/PanopticPool.sol", "affected_contract": "PanopticPool", "affected_function": "haircutPremia", "affected_asset": "premium accounting", "impact_type": "stolen-funds"},
        {"finding_id": "M-09", "title": "Removed liquidity can overflow when mintTokenizedPosition is called", "expected_severity": "Medium", "root_cause": "removed liquidity accumulator can overflow", "bug_class": "overflow", "source_file": "contracts/SemiFungiblePositionManager.sol", "affected_contract": "SemiFungiblePositionManager", "affected_function": "mintTokenizedPosition", "affected_asset": "position liquidity accounting", "impact_type": "bad-debt"},
    ],
    "contest_2003": [
        {"finding_id": "H-01", "title": "Withdrawals can be locked forever if recipient is a contract", "expected_severity": "High", "root_cause": "ETH transfer forwards only 2300 gas to original requester", "bug_class": "eth-transfer", "source_file": "contracts/Withdraw/WithdrawQueue.sol", "affected_contract": "WithdrawQueue", "affected_function": "claim", "affected_asset": "queued withdrawal ETH", "impact_type": "frozen-funds"},
        {"finding_id": "H-02", "title": "Incorrect calculation of queued withdrawals can deflate TVL and increase ezETH mint rate", "expected_severity": "High", "root_cause": "queuedShares lookup checks address(this) instead of token", "bug_class": "accounting-desync", "source_file": "contracts/Delegation/OperatorDelegator.sol", "affected_contract": "OperatorDelegator", "affected_function": "getTokenBalanceFromStrategy", "affected_asset": "TVL and ezETH mint rate", "impact_type": "stolen-funds-or-inflation"},
        {"finding_id": "H-03", "title": "ETH withdrawals from EigenLayer always fail due to OperatorDelegator nonReentrant receive", "expected_severity": "High", "root_cause": "required EigenPod receive path is blocked by nonReentrant", "bug_class": "reentrancy-or-availability", "source_file": "contracts/Delegation/OperatorDelegator.sol", "affected_contract": "OperatorDelegator", "affected_function": "completeQueuedWithdrawal", "affected_asset": "EigenLayer ETH withdrawals", "impact_type": "frozen-funds"},
        {"finding_id": "H-04", "title": "Withdrawals logic allows MEV exploits of TVL changes and zero-slippage zero-fee swaps", "expected_severity": "High", "root_cause": "withdrawal amount fixed at request using stale oracle/TVL", "bug_class": "oracle-manipulation", "source_file": "contracts/Withdraw/WithdrawQueue.sol", "affected_contract": "WithdrawQueue", "affected_function": "withdraw", "affected_asset": "ezETH holders and withdrawal reserves", "impact_type": "stolen-funds"},
        {"finding_id": "H-05", "title": "Withdrawals of rebasing tokens can lead to insolvency and unfair distribution", "expected_severity": "High", "root_cause": "rebasing token balance changes are not accounted in withdrawal reserves", "bug_class": "accounting-desync", "source_file": "contracts/Withdraw/WithdrawQueue.sol", "affected_contract": "WithdrawQueue", "affected_function": "withdraw", "affected_asset": "withdrawal token reserves", "impact_type": "stolen-funds-or-insolvency"},
        {"finding_id": "H-06", "title": "xezETH supply will not represent ezETH 1:1", "expected_severity": "High", "root_cause": "xezETH accounting can diverge from bridged ezETH backing", "bug_class": "accounting-desync", "source_file": "contracts/Bridge/L2/xRenzoDeposit.sol", "affected_contract": "xRenzoDeposit", "affected_function": "deposit", "affected_asset": "xezETH backing", "impact_type": "bad-debt"},
        {"finding_id": "H-07", "title": "DOS of completeQueuedWithdrawal when ERC20 buffer is filled", "expected_severity": "High", "root_cause": "withdrawal completion attempts to fill full buffer and reverts", "bug_class": "denial-of-service", "source_file": "contracts/Delegation/OperatorDelegator.sol", "affected_contract": "OperatorDelegator", "affected_function": "completeQueuedWithdrawal", "affected_asset": "queued withdrawals", "impact_type": "frozen-funds"},
        {"finding_id": "H-08", "title": "Incorrect withdraw queue balance in TVL calculation", "expected_severity": "High", "root_cause": "withdraw queue balance is counted incorrectly in TVL", "bug_class": "accounting-desync", "source_file": "contracts/RestakeManager.sol", "affected_contract": "RestakeManager", "affected_function": "calculateTVLs", "affected_asset": "TVL and ezETH exchange rate", "impact_type": "stolen-funds-or-inflation"},
        {"finding_id": "M-01", "title": "Withdrawals can fail due to deposits reverting in completeQueuedWithdrawal", "expected_severity": "Medium", "root_cause": "completion path deposits into queue and inherits deposit revert conditions", "bug_class": "denial-of-service", "source_file": "contracts/Delegation/OperatorDelegator.sol", "affected_contract": "OperatorDelegator", "affected_function": "completeQueuedWithdrawal", "affected_asset": "queued withdrawals", "impact_type": "frozen-funds"},
        {"finding_id": "M-02", "title": "Withdrawals and claims are meant to be pausable but not possible in practice", "expected_severity": "Medium", "root_cause": "pause controls do not guard withdrawal and claim paths as intended", "bug_class": "access-control", "source_file": "contracts/Withdraw/WithdrawQueue.sol", "affected_contract": "WithdrawQueue", "affected_function": "withdraw", "affected_asset": "withdrawal safety controls", "impact_type": "unauthorized-privileged-action"},
        {"finding_id": "M-03", "title": "Fixed heartbeat used for price validation is too stale for some tokens", "expected_severity": "Medium", "root_cause": "single stale-price heartbeat used across tokens", "bug_class": "oracle-staleness", "source_file": "contracts/Oracle/RenzoOracle.sol", "affected_contract": "RenzoOracle", "affected_function": "lookupTokenValue", "affected_asset": "priced deposits and withdrawals", "impact_type": "bad-debt"},
        {"finding_id": "M-04", "title": "Price updating mechanism can break", "expected_severity": "Medium", "root_cause": "oracle update path can become unavailable or stale", "bug_class": "oracle-staleness", "source_file": "contracts/Bridge/L2/Oracle/RenzoOracleL2.sol", "affected_contract": "RenzoOracleL2", "affected_function": "setOracleAddress", "affected_asset": "L2 price updates", "impact_type": "bad-debt-or-availability"},
        {"finding_id": "M-05", "title": "calculateTVL may run out of gas for modest number of operators and tokens", "expected_severity": "Medium", "root_cause": "unbounded TVL loops over operators and tokens", "bug_class": "denial-of-service", "source_file": "contracts/RestakeManager.sol", "affected_contract": "RestakeManager", "affected_function": "calculateTVLs", "affected_asset": "deposits withdrawals and trades", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-06", "title": "xRenzoBridge uses block.timestamp as dependency", "expected_severity": "Medium", "root_cause": "bridge price message depends on manipulable timestamp", "bug_class": "time-dependency", "source_file": "contracts/Bridge/L1/xRenzoBridge.sol", "affected_contract": "xRenzoBridge", "affected_function": "sendPrice", "affected_asset": "bridge price updates", "impact_type": "bad-debt"},
        {"finding_id": "M-07", "title": "Lack of slippage and deadline during withdraw and deposit", "expected_severity": "Medium", "root_cause": "deposit and withdraw paths lack user slippage/deadline controls", "bug_class": "slippage", "source_file": "contracts/RestakeManager.sol", "affected_contract": "RestakeManager", "affected_function": "deposit", "affected_asset": "depositor and withdrawer value", "impact_type": "stolen-funds"},
        {"finding_id": "M-08", "title": "Not handling the failure of cross chain messaging", "expected_severity": "Medium", "root_cause": "bridge send failure has no recovery handling", "bug_class": "bridge-message-failure", "source_file": "contracts/Bridge/L1/xRenzoBridge.sol", "affected_contract": "xRenzoBridge", "affected_function": "sendPrice", "affected_asset": "cross-chain bridge messages", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-09", "title": "Deposits revert if amount deposited is less than bufferToFill", "expected_severity": "Medium", "root_cause": "deposit path assumes deposit amount can fill buffer", "bug_class": "denial-of-service", "source_file": "contracts/RestakeManager.sol", "affected_contract": "RestakeManager", "affected_function": "deposit", "affected_asset": "deposits", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-10", "title": "Potential arbitrage opportunity in xRenzoDeposit L2 contract", "expected_severity": "Medium", "root_cause": "L2 deposit price can be arbitraged against stale exchange rate", "bug_class": "oracle-manipulation", "source_file": "contracts/Bridge/L2/xRenzoDeposit.sol", "affected_contract": "xRenzoDeposit", "affected_function": "deposit", "affected_asset": "xezETH exchange rate", "impact_type": "stolen-funds"},
        {"finding_id": "M-11", "title": "Fetched price from the oracle is not stored in xRenzoDeposit", "expected_severity": "Medium", "root_cause": "fetched oracle price is not persisted for accounting", "bug_class": "oracle-accounting", "source_file": "contracts/Bridge/L2/xRenzoDeposit.sol", "affected_contract": "xRenzoDeposit", "affected_function": "deposit", "affected_asset": "L2 pricing/accounting", "impact_type": "bad-debt"},
        {"finding_id": "M-12", "title": "Incorrect exchange rate provided to Balancer pools", "expected_severity": "Medium", "root_cause": "rate provider returns incorrect exchange rate", "bug_class": "oracle-accounting", "source_file": "contracts/RateProvider/BalancerRateProvider.sol", "affected_contract": "BalancerRateProvider", "affected_function": "getRate", "affected_asset": "Balancer pool LPs", "impact_type": "stolen-funds"},
        {"finding_id": "M-13", "title": "Pending withdrawals prevent safe removal of collateral assets", "expected_severity": "Medium", "root_cause": "collateral removal ignores pending withdrawals", "bug_class": "incomplete-path", "source_file": "contracts/RestakeManager.sol", "affected_contract": "RestakeManager", "affected_function": "removeCollateralToken", "affected_asset": "pending withdrawal reserves", "impact_type": "frozen-funds"},
        {"finding_id": "M-14", "title": "stETH/ETH feed opens two way deposit withdrawal arbitrage", "expected_severity": "Medium", "root_cause": "stETH/ETH price feed permits stale two-way arbitrage", "bug_class": "oracle-manipulation", "source_file": "contracts/Oracle/RenzoOracle.sol", "affected_contract": "RenzoOracle", "affected_function": "lookupTokenValue", "affected_asset": "ezETH holders", "impact_type": "stolen-funds"},
    ],
    "contest_3001": [
        {"finding_id": "H-01", "title": "Chained signature with checkpoint usage disabled can bypass all checkpointer validation", "expected_severity": "High", "root_cause": "chained signature path permits missing checkpointer usage flag and skips snapshot validation", "bug_class": "signature-validation-bypass", "source_file": "src/modules/auth/BaseSig.sol", "affected_contract": "BaseSig", "affected_function": "recover", "affected_asset": "wallet authorization and funds controlled by stale signer configurations", "impact_type": "unauthorized-privileged-action"},
        {"finding_id": "H-02", "title": "Partial signature replay frontrunning attack on session calls", "expected_severity": "High", "root_cause": "session call signatures are bound per call instead of to the complete payload and remain reusable when revert rolls back nonce consumption", "bug_class": "signature-replay", "source_file": "src/extensions/sessions/SessionSig.sol", "affected_contract": "SessionSig", "affected_function": "hashCallWithReplayProtection", "affected_asset": "wallet session calls and wallet funds", "impact_type": "stolen-funds"},
        {"finding_id": "M-01", "title": "Session signatures replay across wallets due to missing wallet binding", "expected_severity": "Medium", "root_cause": "session signature preimage omits the executing wallet address", "bug_class": "signature-replay", "source_file": "src/extensions/sessions/SessionSig.sol", "affected_contract": "SessionSig", "affected_function": "hashCallWithReplayProtection", "affected_asset": "sibling wallet funds sharing configuration and nonce state", "impact_type": "stolen-funds"},
        {"finding_id": "M-02", "title": "Static signatures bound to caller revert under ERC-4337 causing DoS", "expected_severity": "Medium", "root_cause": "validateUserOp uses an external self-call so static signature caller binding compares against the wallet instead of the EntryPoint", "bug_class": "denial-of-service", "source_file": "src/modules/ERC4337v07.sol", "affected_contract": "ERC4337v07", "affected_function": "validateUserOp", "affected_asset": "ERC-4337 wallet operations using caller-bound static signatures", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-03", "title": "BaseAuth.recoverSapientSignature returns a constant instead of signer image hash breaking sapient signer flows", "expected_severity": "Medium", "root_cause": "recoverSapientSignature violates ISapient by returning a constant rather than the signer image hash", "bug_class": "invalid-validation", "source_file": "src/modules/auth/BaseAuth.sol", "affected_contract": "BaseAuth", "affected_function": "recoverSapientSignature", "affected_asset": "sapient signer authorization flows", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-04", "title": "Factory deploy reverts instead of returning address when account already exists", "expected_severity": "Medium", "root_cause": "factory deployment path does not handle already deployed account addresses as specified", "bug_class": "incomplete-path", "source_file": "src/Factory.sol", "affected_contract": "Factory", "affected_function": "deploy", "affected_asset": "wallet deployment and account recovery flows", "impact_type": "frozen-funds-or-availability"},
    ],
    "contest_3002": [
        {"finding_id": "M-01", "title": "Oracle Data Corruption via Storage Key Collision", "expected_severity": "Medium", "root_cause": "oracle counts and snapshot storage keys can collide because slots are derived from raw token addresses and shifted token addresses", "bug_class": "storage-collision", "source_file": "src/extensions/Oracle.sol", "affected_contract": "Oracle", "affected_function": "maybeInsertSnapshot", "affected_asset": "oracle historical price and liquidity snapshots", "impact_type": "bad-pricing-or-oracle-corruption"},
        {"finding_id": "M-02", "title": "TWAMM Instant Orders Can Steal Historical Rewards", "expected_severity": "Medium", "root_cause": "TWAMM orders created at block.timestamp equal startTime do not register startTime reward rates", "bug_class": "accounting-desync", "source_file": "src/extensions/TWAMM.sol", "affected_contract": "TWAMM", "affected_function": "handleForwardData", "affected_asset": "TWAMM order rewards", "impact_type": "stolen-funds"},
        {"finding_id": "M-03", "title": "Wrong rounding direction in DurationRemaining leads to value loss from TWAMM extension and Temporarily Freezing of a Pool", "expected_severity": "Medium", "root_cause": "remaining sell amount is rounded up when decreasing sale rate causing cumulative over-refunds and saved balance debt", "bug_class": "rounding-accounting", "source_file": "src/extensions/TWAMM.sol", "affected_contract": "TWAMM", "affected_function": "handleForwardData", "affected_asset": "TWAMM extension saved balances and pool liveness", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-04", "title": "Router does not check if Exact Out Single Swap was partial leading to unexpected results for the users", "expected_severity": "Medium", "root_cause": "single exact-out swap path checks maximum input but not that the exact requested output was fully delivered", "bug_class": "incomplete-validation", "source_file": "src/Router.sol", "affected_contract": "Router", "affected_function": "handleLockData", "affected_asset": "swap user output amounts", "impact_type": "stolen-funds-or-user-loss"},
    ],
    "contest_3003": [
        {"finding_id": "M-01", "title": "Same heartbeat for multiple price feeds is vulnerable", "expected_severity": "Medium", "root_cause": "single allowedPriceUpdateDelay heartbeat is reused for feeds with different freshness requirements", "bug_class": "oracle-staleness", "source_file": "contracts/capital-protocol/ChainLinkDataConsumer.sol", "affected_contract": "ChainLinkDataConsumer", "affected_function": "getChainLinkDataFeedLatestAnswer", "affected_asset": "priced deposits withdrawals and reward accounting", "impact_type": "bad-debt-or-availability"},
        {"finding_id": "M-02", "title": "Inconsistent balance accounting in stETH deposits leads to DOS of core functions and reward loss", "expected_severity": "Medium", "root_cause": "Distributor.supply records requested stETH amount rather than actual balance delta after stETH transfer rounding", "bug_class": "accounting-desync", "source_file": "contracts/capital-protocol/Distributor.sol", "affected_contract": "Distributor", "affected_function": "supply", "affected_asset": "stETH deposit pool accounting and rewards", "impact_type": "frozen-funds-or-reward-loss"},
        {"finding_id": "M-03", "title": "Protocol doesn’t properly handle Aave Pool changes", "expected_severity": "Medium", "root_cause": "setAavePool changes pool address without revoking old approvals or approving the new pool for existing deposit pools", "bug_class": "incomplete-upgrade-path", "source_file": "contracts/capital-protocol/Distributor.sol", "affected_contract": "Distributor", "affected_function": "setAavePool", "affected_asset": "Aave strategy deposit pool funds and operations", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-04", "title": "Yield withdrawal blocked by zero reward early return", "expected_severity": "Medium", "root_cause": "distributeRewards returns early when period rewards are zero and skips lastUnderlyingBalance update needed for yield withdrawal", "bug_class": "incomplete-path", "source_file": "contracts/capital-protocol/Distributor.sol", "affected_contract": "Distributor", "affected_function": "distributeRewards", "affected_asset": "post-reward-period yield", "impact_type": "frozen-funds"},
    ],
    "contest_4001": [
        {"finding_id": "M-01", "title": "User can bypass staking restrictions through composer and deposit on another chain", "expected_severity": "Medium", "root_cause": "cross-chain deposit-and-send path mints vault shares without checking the depositor's SOFT_RESTRICTED_STAKER_ROLE", "bug_class": "access-control", "source_file": "src/token/wiTRY/crosschain/libraries/VaultComposerSync.sol", "affected_contract": "VaultComposerSync", "affected_function": "_depositAndSend", "affected_asset": "restricted staking access and wiTRY shares minted on spoke chains", "impact_type": "unauthorized-privileged-action"},
        {"finding_id": "M-02", "title": "Cross-chain unstake and fast redeem operations fail due to minAmountLD not accounting for LayerZero dust removal", "expected_severity": "Medium", "root_cause": "cross-chain asset sends set minAmountLD equal to amountLD even though LayerZero OFT removes decimal dust before delivery", "bug_class": "denial-of-service", "source_file": "src/token/wiTRY/crosschain/wiTryVaultComposer.sol", "affected_contract": "wiTryVaultComposer", "affected_function": "_handleUnstake", "affected_asset": "cross-chain unstake and fast-redeem iTRY transfers", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-03", "title": "Incompatibility with Account Abstraction and Multisigs due to enforced address symmetry in cross chain unstaking", "expected_severity": "Medium", "root_cause": "UnstakeMessenger hardcodes the hub-chain recipient to msg.sender and provides no destination recipient override", "bug_class": "incomplete-path", "source_file": "src/token/wiTRY/crosschain/UnstakeMessenger.sol", "affected_contract": "UnstakeMessenger", "affected_function": "unstake", "affected_asset": "AA and multisig cross-chain unstake proceeds", "impact_type": "frozen-funds"},
    ],
    "contest_4002": [
        {"finding_id": "M-01", "title": "Minimum Reward-Per-Hour Validation Applied to Gross Instead of Net Amount", "expected_severity": "Medium", "root_cause": "_createCampaign validates the minimum reward-per-hour threshold against the gross campaign amount before deducting protocol fees", "bug_class": "accounting-desync", "source_file": "contracts/DistributionCreator.sol", "affected_contract": "DistributionCreator", "affected_function": "_createCampaign", "affected_asset": "campaign reward rates paid to Merkl recipients", "impact_type": "stolen-funds-or-user-loss"},
        {"finding_id": "M-02", "title": "Improper Error Handling of onClaim Callback in _claim Function", "expected_severity": "Medium", "root_cause": "_claim swallows external onClaim reverts while invalid callback return values revert inside the try success branch", "bug_class": "denial-of-service", "source_file": "contracts/Distributor.sol", "affected_contract": "Distributor", "affected_function": "_claim", "affected_asset": "claim batches and recipient callback invariants", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-03", "title": "Multi-step campaign overrides are anchored to the original campaign, making later overrides impossible", "expected_severity": "Medium", "root_cause": "overrideCampaign validates every new override against the original campaign parameters instead of the current effective override", "bug_class": "incomplete-path", "source_file": "contracts/DistributionCreator.sol", "affected_contract": "DistributionCreator", "affected_function": "overrideCampaign", "affected_asset": "campaign override lifecycle and creator campaign management", "impact_type": "frozen-funds-or-availability"},
    ],
    "contest_4003": [
        {"finding_id": "H-01", "title": "Attacker can steal JackpotTicketNFTs from JackpotBridgeManager", "expected_severity": "High", "root_cause": "claimWinnings executes user-controlled arbitrary bridge call data from the JackpotBridgeManager address and only verifies USDC balance decrease", "bug_class": "access-control", "source_file": "contracts/JackpotBridgeManager.sol", "affected_contract": "JackpotBridgeManager", "affected_function": "_bridgeFunds", "affected_asset": "JackpotTicketNFTs held in bridge-manager custody", "impact_type": "stolen-funds"},
        {"finding_id": "H-02", "title": "Unoptimized subset matches counting implementation will exceed tx gas limit on base chain", "expected_severity": "High", "root_cause": "winner settlement regenerates all normal-ball subsets inside nested bonusball and tier loops, making countTierMatchesWithBonusball exceed block gas limits", "bug_class": "denial-of-service", "source_file": "contracts/lib/TicketComboTracker.sol", "affected_contract": "TicketComboTracker", "affected_function": "countTierMatchesWithBonusball", "affected_asset": "jackpot drawing settlement and user winnings", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "H-03", "title": "LP pool cap may be exceeded on drawing settlement", "expected_severity": "High", "root_cause": "processDrawingSettlement computes the next LP value without enforcing the same LP pool cap and bit-vector bounds used for parameter updates", "bug_class": "accounting-desync", "source_file": "contracts/JackpotLPManager.sol", "affected_contract": "JackpotLPManager", "affected_function": "processDrawingSettlement", "affected_asset": "LP pool cap, drawing parameters, and ticket-combo tracking", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-01", "title": "Global Variable Manipulation During Active Draw Alters End Result", "expected_severity": "Medium", "root_cause": "owner-set global configuration values are read during settlement after tickets are bought and can be changed during an active drawing", "bug_class": "business-logic", "source_file": "contracts/Jackpot.sol", "affected_contract": "Jackpot", "affected_function": "setPayoutCalculator", "affected_asset": "drawing settlement integrity, payouts, fees, and randomness path", "impact_type": "unauthorized-privileged-action"},
        {"finding_id": "M-02", "title": "Incorrect ticket price reference in JackpotBridgeManager causes user overpayment after price updates", "expected_severity": "Medium", "root_cause": "JackpotBridgeManager.buyTickets prices tickets using the mutable global jackpot.ticketPrice instead of the current drawing's frozen ticket price", "bug_class": "accounting-desync", "source_file": "contracts/JackpotBridgeManager.sol", "affected_contract": "JackpotBridgeManager", "affected_function": "buyTickets", "affected_asset": "cross-chain ticket buyer USDC", "impact_type": "stolen-funds-or-user-loss"},
        {"finding_id": "M-03", "title": "Deliberately increasing liquidity can DoS updates to the protocol's governance parameters", "expected_severity": "Medium", "root_cause": "setLPPoolCap reverts when lpPoolTotal plus pendingDeposits exceeds the new cap, allowing LP deposits to block parameter updates", "bug_class": "denial-of-service", "source_file": "contracts/JackpotLPManager.sol", "affected_contract": "JackpotLPManager", "affected_function": "setLPPoolCap", "affected_asset": "governance parameter updates that recalculate LP pool cap", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-04", "title": "lpEarnings generated in emergency mode become stuck on the contract", "expected_severity": "Medium", "root_cause": "_payReferrersWinnings can add referral shares to current drawing lpEarnings after emergency mode, but emergency mode prevents settlement from rolling those earnings into LP accounting", "bug_class": "incomplete-path", "source_file": "contracts/Jackpot.sol", "affected_contract": "Jackpot", "affected_function": "_payReferrersWinnings", "affected_asset": "LP earnings accrued from referral win shares", "impact_type": "frozen-funds"},
        {"finding_id": "M-05", "title": "Randomness can be exploited in some cases", "expected_severity": "Medium", "root_cause": "_getScaledRandomness derives normal balls and bonus ball from the same seed, so equal normal and bonus ranges make the bonus ball overlap a normal ball", "bug_class": "randomness", "source_file": "contracts/ScaledEntropyProvider.sol", "affected_contract": "ScaledEntropyProvider", "affected_function": "_getScaledRandomness", "affected_asset": "jackpot odds and prize pool fairness", "impact_type": "stolen-funds"},
        {"finding_id": "M-06", "title": "Changes to Pyth entropy provider used by ScaledEntropyProvider allow attacker to fix jackpot result", "expected_severity": "Medium", "root_cause": "pending entropy requests are keyed only by sequence number while different Pyth providers can reuse the same sequence after entropyProvider changes", "bug_class": "randomness", "source_file": "contracts/ScaledEntropyProvider.sol", "affected_contract": "ScaledEntropyProvider", "affected_function": "_storePendingRequest", "affected_asset": "jackpot randomness requests and winning numbers", "impact_type": "stolen-funds"},
        {"finding_id": "M-07", "title": "Changing Entropy Provider During Active Drawing Causes Permanent Protocol Lock and Callback Failure", "expected_severity": "Medium", "root_cause": "Jackpot.setEntropy can change the entropy contract while a drawing has an outstanding request, causing the original callback to fail onlyEntropy and leaving jackpotLock set", "bug_class": "denial-of-service", "source_file": "contracts/Jackpot.sol", "affected_contract": "Jackpot", "affected_function": "setEntropy", "affected_asset": "active drawing settlement and ticket funds", "impact_type": "frozen-funds"},
        {"finding_id": "M-08", "title": "Changing Payout Calculator During Active Drawing Causes Loss of Unclaimed Winnings", "expected_severity": "Medium", "root_cause": "Jackpot.setPayoutCalculator can switch the payout calculator for an active drawing, so unclaimed winnings recorded in the previous calculator are no longer read on claims", "bug_class": "incomplete-path", "source_file": "contracts/Jackpot.sol", "affected_contract": "Jackpot", "affected_function": "setPayoutCalculator", "affected_asset": "unclaimed jackpot winnings", "impact_type": "stolen-funds-or-frozen-funds"},
    ],
    "contest_5001": [
        {"finding_id": "H-01", "title": "Assets deposited before calculating shares amount to mint will cause users to mint less shares", "expected_severity": "High", "root_cause": "deposit transfers assets into voting escrow before calculating shares, so the user's own assets dilute the mint calculation", "bug_class": "accounting-desync", "source_file": "ve33/contracts/GovernanceHYBR.sol", "affected_contract": "GovernanceHYBR", "affected_function": "deposit", "affected_asset": "gHYBR shares and deposited HYBR", "impact_type": "stolen-funds-or-user-loss"},
        {"finding_id": "M-01", "title": "CLFactory ignores dynamic fees above 10% and silently falls back to default", "expected_severity": "Medium", "root_cause": "factory caps dynamic fee reads at 10 percent while the module can be configured above that value", "bug_class": "incomplete-validation", "source_file": "cl/contracts/core/CLFactory.sol", "affected_contract": "CLFactory", "affected_function": "getSwapFee", "affected_asset": "pool fee revenue and trading protection", "impact_type": "stolen-funds-or-user-loss"},
        {"finding_id": "M-02", "title": "Users emergency withdrawing will lose all past accrued rewards", "expected_severity": "Medium", "root_cause": "emergencyWithdraw clears stake without updating accrued rewards first", "bug_class": "accounting-desync", "source_file": "ve33/contracts/GaugeV2.sol", "affected_contract": "GaugeV2", "affected_function": "emergencyWithdraw", "affected_asset": "user reward accrual and reward tokens", "impact_type": "stolen-funds-or-frozen-funds"},
        {"finding_id": "M-03", "title": "First depositor attack possible through multiple attack paths because the deposit function does not check 0 shares received", "expected_severity": "Medium", "root_cause": "deposit allows zero-share mints and totalAssets can be inflated by donations or external deposit paths", "bug_class": "erc4626-inflation", "source_file": "ve33/contracts/GovernanceHYBR.sol", "affected_contract": "GovernanceHYBR", "affected_function": "deposit", "affected_asset": "depositor HYBR and gHYBR share accounting", "impact_type": "stolen-funds"},
        {"finding_id": "M-04", "title": "Dust vote on one pool prevents poke()", "expected_severity": "Medium", "root_cause": "poke reverts when a dust vote rounds pool weight to zero instead of skipping that pool", "bug_class": "denial-of-service", "source_file": "ve33/contracts/VoterV3.sol", "affected_contract": "VoterV3", "affected_function": "poke", "affected_asset": "vote weight decay and gauge reward distribution", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-05", "title": "Rollover rewards are permanently lost due to flawed rewardRate calculation", "expected_severity": "Medium", "root_cause": "notifyRewardAmount computes rewardRate from only the new reward and excludes rollover rewards", "bug_class": "accounting-desync", "source_file": "ve33/contracts/CLGauge/GaugeCL.sol", "affected_contract": "GaugeCL", "affected_function": "notifyRewardAmount", "affected_asset": "CL gauge rollover rewards", "impact_type": "stolen-funds-or-frozen-funds"},
        {"finding_id": "M-06", "title": "ClaimFees steals staking rewards", "expected_severity": "Medium", "root_cause": "claimFees claims staking reward tokens through the fee path and sends rewards to the wrong recipient", "bug_class": "accounting-desync", "source_file": "ve33/contracts/CLGauge/GaugeCL.sol", "affected_contract": "GaugeCL", "affected_function": "claimFees", "affected_asset": "staking rewards", "impact_type": "stolen-funds"},
        {"finding_id": "M-07", "title": "Claiming rewards in GovernanceHYBR will always revert", "expected_severity": "Medium", "root_cause": "GovernanceHYBR reward claiming uses an incompatible or unreachable claim path", "bug_class": "incomplete-path", "source_file": "ve33/contracts/GovernanceHYBR.sol", "affected_contract": "GovernanceHYBR", "affected_function": "getReward", "affected_asset": "GovernanceHYBR rewards", "impact_type": "frozen-funds"},
        {"finding_id": "M-08", "title": "Incorrect voting power calculation when create_lock and increase_amount are called in the same transaction", "expected_severity": "Medium", "root_cause": "same-transaction lock creation and amount increase uses stale checkpointed voting power", "bug_class": "accounting-desync", "source_file": "ve33/contracts/VotingEscrow.sol", "affected_contract": "VotingEscrow", "affected_function": "increase_amount", "affected_asset": "ve voting power and reward allocation", "impact_type": "stolen-funds-or-user-loss"},
        {"finding_id": "M-09", "title": "CL gauge accepts unverified pools, allowing malicious pool to brick distribution", "expected_severity": "Medium", "root_cause": "gauge creation accepts an unverified CL pool and later distribution interacts with malicious pool behavior", "bug_class": "access-control", "source_file": "ve33/contracts/GaugeManager.sol", "affected_contract": "GaugeManager", "affected_function": "createGauge", "affected_asset": "gauge distribution and rewards", "impact_type": "frozen-funds-or-availability"},
    ],
    "contest_5003": [
        {"finding_id": "H-01", "title": "Buffer Silently Locks Staked HYPE in Contract Without Using Them For Withdrawals Or Providing A Way To Be Pulled Out Or Moved To L1", "expected_severity": "High", "root_cause": "cancelled withdrawals consume buffer accounting but redelegation does not restore or move the HYPE correctly", "bug_class": "accounting-desync", "source_file": "src/StakingManager.sol", "affected_contract": "StakingManager", "affected_function": "cancelWithdrawal", "affected_asset": "staked HYPE buffer", "impact_type": "frozen-funds"},
        {"finding_id": "H-02", "title": "Users Who Queue Withdrawal Before A Slashing Event Disadvantage Users Who Queue After And Eventually Leads To Loss Of Funds For Them", "expected_severity": "High", "root_cause": "queued withdrawals store pre-slash HYPE amounts and confirm against stale exchange-rate assumptions", "bug_class": "accounting-desync", "source_file": "src/StakingAccountant.sol", "affected_contract": "StakingAccountant", "affected_function": "kHYPEToHYPE", "affected_asset": "KHYPE/HYPE withdrawal accounting", "impact_type": "stolen-funds"},
        {"finding_id": "H-03", "title": "Mishandling of receiving HYPE in the StakingManager, user can’t confirm withdrawal and inflate the exchange ratio", "expected_severity": "High", "root_cause": "receive() blindly calls stake when HYPE returns from HyperCore, restaking withdrawal funds instead of making them claimable", "bug_class": "incomplete-path", "source_file": "src/StakingManager.sol", "affected_contract": "StakingManager", "affected_function": "receive", "affected_asset": "withdrawal HYPE and KHYPE exchange ratio", "impact_type": "frozen-funds-or-inflation"},
        {"finding_id": "M-01", "title": "Incorrect Balance Check in Validator Redelegation Process May Block Legitimate Rebalancing Operations", "expected_severity": "Medium", "root_cause": "redelegation checks HyperEVM balance even though redelegated funds are on HyperCore", "bug_class": "incomplete-validation", "source_file": "src/StakingManager.sol", "affected_contract": "StakingManager", "affected_function": "processValidatorRedelegation", "affected_asset": "validator rebalancing operations", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-02", "title": "Missing withdrawal pause check in confirmWithdrawal allows bypassing withdrawal restrictions", "expected_severity": "Medium", "root_cause": "confirmWithdrawal lacks the withdrawal-specific pause modifier", "bug_class": "access-control", "source_file": "src/StakingManager.sol", "affected_contract": "StakingManager", "affected_function": "confirmWithdrawal", "affected_asset": "withdrawal pause controls", "impact_type": "unauthorized-privileged-action"},
        {"finding_id": "M-03", "title": "Inconsistent State Restoration in cancelWithdrawal Function", "expected_severity": "Medium", "root_cause": "cancelWithdrawal refunds KHYPE but does not restore hypeBuffer or pending withdrawal state", "bug_class": "accounting-desync", "source_file": "src/StakingManager.sol", "affected_contract": "StakingManager", "affected_function": "cancelWithdrawal", "affected_asset": "withdrawal buffer and pending operations", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-04", "title": "Processing all withdrawals before all deposits can cause some deposit to not be delegated in processL1Operations", "expected_severity": "Medium", "root_cause": "processL1Operations processes withdrawals and deposits in an order that can strand or skip deposit delegation capacity", "bug_class": "incomplete-path", "source_file": "src/StakingManager.sol", "affected_contract": "StakingManager", "affected_function": "processL1Operations", "affected_asset": "HYPE deposits and delegation queue", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-05", "title": "Attacker can partially DoS L1 operations in StakingManager by making huge number of deposits", "expected_severity": "Medium", "root_cause": "unbounded user-created deposit operations can exhaust L1 operation processing capacity", "bug_class": "denial-of-service", "source_file": "src/StakingManager.sol", "affected_contract": "StakingManager", "affected_function": "stake", "affected_asset": "L1 operation processing", "impact_type": "frozen-funds-or-availability"},
    ],
    "contest_5004_fallback": [
        {"finding_id": "H-01", "title": "Lack of access control in AgentNftV2::addValidator() enables unauthorized validator injection and causes reward accounting inconsistencies", "expected_severity": "High", "root_cause": "addValidator can be called without required authorization", "bug_class": "access-control", "source_file": "contracts/virtualPersona/AgentNftV2.sol", "affected_contract": "AgentNftV2", "affected_function": "addValidator", "affected_asset": "validator set and reward accounting", "impact_type": "unauthorized-privileged-action"},
        {"finding_id": "H-02", "title": "Anybody can control a user’s delegate by calling AgentVeToken.stake() with 1 wei", "expected_severity": "High", "root_cause": "stake updates delegation for a target user with dust stake without ownership authorization", "bug_class": "access-control", "source_file": "contracts/virtualPersona/AgentVeToken.sol", "affected_contract": "AgentVeToken", "affected_function": "stake", "affected_asset": "delegation and rewards", "impact_type": "unauthorized-privileged-action"},
        {"finding_id": "H-03", "title": "Public ServiceNft::updateImpact call leads to cascading issue", "expected_severity": "High", "root_cause": "updateImpact is public and lets arbitrary callers manipulate impact accounting", "bug_class": "access-control", "source_file": "contracts/contribution/ServiceNft.sol", "affected_contract": "ServiceNft", "affected_function": "updateImpact", "affected_asset": "service NFT impact and rewards", "impact_type": "unauthorized-privileged-action"},
        {"finding_id": "H-04", "title": "Public ContributionNft::mint leads to cascading issues / loss of funds", "expected_severity": "High", "root_cause": "ContributionNft mint is publicly reachable without intended authorization", "bug_class": "access-control", "source_file": "contracts/contribution/ContributionNft.sol", "affected_contract": "ContributionNft", "affected_function": "mint", "affected_asset": "contribution NFTs and related rewards", "impact_type": "stolen-funds-or-unauthorized-privileged-action"},
        {"finding_id": "H-05", "title": "ValidatorRegistry::validatorScore/getPastValidatorScore allows validator to earn full rewards without actually engaging with the protocol", "expected_severity": "High", "root_cause": "validator score lookups can return full reward weight without validating actual engagement", "bug_class": "accounting-desync", "source_file": "contracts/virtualPersona/ValidatorRegistry.sol", "affected_contract": "ValidatorRegistry", "affected_function": "validatorScore", "affected_asset": "validator rewards", "impact_type": "stolen-funds"},
        {"finding_id": "H-06", "title": "Missing prevAgentId update in promptMulti() function may cause token loss by transferring to address(0)", "expected_severity": "High", "root_cause": "promptMulti fails to update prevAgentId while iterating agent prompts", "bug_class": "accounting-desync", "source_file": "contracts/AgentInference.sol", "affected_contract": "AgentInference", "affected_function": "promptMulti", "affected_asset": "agent prompt payments", "impact_type": "stolen-funds"},
        {"finding_id": "M-01", "title": "Attacker can prevent user from executing application registered through initFromToken() in AgentFactoryV4", "expected_severity": "Medium", "root_cause": "application registration through initFromToken can be griefed or preempted by an attacker", "bug_class": "denial-of-service", "source_file": "contracts/virtualPersona/AgentFactoryV4.sol", "affected_contract": "AgentFactoryV4", "affected_function": "initFromToken", "affected_asset": "agent application execution", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-02", "title": "Missing slippage protection on buy and sell", "expected_severity": "Medium", "root_cause": "router buy and sell paths execute without user-provided slippage constraints", "bug_class": "incomplete-validation", "source_file": "contracts/fun/FRouter.sol", "affected_contract": "FRouter", "affected_function": "buy", "affected_asset": "trader tokens", "impact_type": "stolen-funds-or-user-loss"},
        {"finding_id": "M-03", "title": "Slippage protection in AgentTax::dcaSell and BondingTax::swapForAsset is calculated at execution time", "expected_severity": "Medium", "root_cause": "minimum output is derived from the same execution-time price instead of a user-controlled bound", "bug_class": "incomplete-validation", "source_file": "contracts/tax/BondingTax.sol", "affected_contract": "BondingTax", "affected_function": "swapForAsset", "affected_asset": "tax swap proceeds", "impact_type": "stolen-funds-or-user-loss"},
        {"finding_id": "M-04", "title": "Launched tokens are vulnerable to flashloan attacks forcing premature graduation, allowing reward manipulation", "expected_severity": "Medium", "root_cause": "graduation logic can be forced by temporary flashloan-inflated liquidity or price state", "bug_class": "oracle-manipulation", "source_file": "contracts/fun/Bonding.sol", "affected_contract": "Bonding", "affected_function": "launchFor", "affected_asset": "launched token rewards and graduation state", "impact_type": "stolen-funds"},
        {"finding_id": "M-05", "title": "Division in Bonding.sol._openTradingOnUniswap() results in an incorrect lpSupply, higher vaultSupply, and dust AgentTokens getting locked in FPair", "expected_severity": "Medium", "root_cause": "open trading division math misallocates LP and vault supply", "bug_class": "accounting-desync", "source_file": "contracts/fun/Bonding.sol", "affected_contract": "Bonding", "affected_function": "_openTradingOnUniswap", "affected_asset": "LP supply, vault supply, and AgentTokens", "impact_type": "stolen-funds-or-frozen-funds"},
        {"finding_id": "M-06", "title": "BondingTax has invalid slippage implementation", "expected_severity": "Medium", "root_cause": "BondingTax slippage calculation does not protect the actual swap", "bug_class": "incomplete-validation", "source_file": "contracts/tax/BondingTax.sol", "affected_contract": "BondingTax", "affected_function": "swapForAsset", "affected_asset": "tax swap proceeds", "impact_type": "stolen-funds-or-user-loss"},
        {"finding_id": "M-07", "title": "amountOutMin passed in as 0 in AgentToken::_swapTax leads to loss of funds due to slippage", "expected_severity": "Medium", "root_cause": "_swapTax hardcodes amountOutMin to zero", "bug_class": "incomplete-validation", "source_file": "contracts/virtualPersona/AgentToken.sol", "affected_contract": "AgentToken", "affected_function": "_swapTax", "affected_asset": "tax swap funds", "impact_type": "stolen-funds-or-user-loss"},
        {"finding_id": "M-08", "title": "Score in AgentDAO is not an accurate measure and can be artificially inflated by spamming proposals", "expected_severity": "Medium", "root_cause": "proposal spam can inflate score without corresponding valid contribution", "bug_class": "business-logic", "source_file": "contracts/virtualPersona/AgentDAO.sol", "affected_contract": "AgentDAO", "affected_function": "propose", "affected_asset": "DAO scores and rewards", "impact_type": "stolen-funds-or-unauthorized-privileged-action"},
        {"finding_id": "M-09", "title": "Functions in FERC20 can’t be invoked", "expected_severity": "Medium", "root_cause": "FERC20 call flow or access pattern makes required functions uncallable", "bug_class": "denial-of-service", "source_file": "contracts/fun/FERC20.sol", "affected_contract": "FERC20", "affected_function": "transfer", "affected_asset": "FERC20 token operations", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-10", "title": "Missing totalSupply reduction in burnFrom allows supply manipulation (ERC20 Violation)", "expected_severity": "Medium", "root_cause": "burnFrom decreases balances without reducing totalSupply", "bug_class": "accounting-desync", "source_file": "contracts/fun/FERC20.sol", "affected_contract": "FERC20", "affected_function": "burnFrom", "affected_asset": "token supply accounting", "impact_type": "stolen-funds-or-inflation"},
        {"finding_id": "M-11", "title": "AgentDAO::_castVote doesn’t check the array of votes emitted, allowing the user to increase the ELO of a contribution", "expected_severity": "Medium", "root_cause": "_castVote does not validate emitted vote array used for Elo battles", "bug_class": "business-logic", "source_file": "contracts/virtualPersona/AgentDAO.sol", "affected_contract": "AgentDAO", "affected_function": "_castVote", "affected_asset": "contribution Elo and rewards", "impact_type": "stolen-funds-or-unauthorized-privileged-action"},
        {"finding_id": "M-12", "title": "No slippage protection during adding liquidity to uniswap", "expected_severity": "Medium", "root_cause": "liquidity add path omits minimum amount bounds", "bug_class": "incomplete-validation", "source_file": "contracts/virtualPersona/AgentFactoryV4.sol", "affected_contract": "AgentFactoryV4", "affected_function": "executeApplication", "affected_asset": "liquidity provisioning funds", "impact_type": "stolen-funds-or-user-loss"},
        {"finding_id": "M-13", "title": "Removal of a liquidity pool on AgentToken::removeLiquidityPool still incurs taxes on swaps", "expected_severity": "Medium", "root_cause": "removeLiquidityPool does not clear all state used by swap tax logic", "bug_class": "incomplete-path", "source_file": "contracts/virtualPersona/AgentToken.sol", "affected_contract": "AgentToken", "affected_function": "removeLiquidityPool", "affected_asset": "swap users and taxes", "impact_type": "stolen-funds-or-user-loss"},
        {"finding_id": "M-14", "title": "VotesUpgradeable::delegate bypasses the addValidator call, leads to a non-validator holding voting power along with loss of rewards", "expected_severity": "Medium", "root_cause": "delegate path bypasses validator registration hooks", "bug_class": "access-control", "source_file": "contracts/virtualPersona/AgentVeToken.sol", "affected_contract": "AgentVeToken", "affected_function": "delegate", "affected_asset": "validator voting power and rewards", "impact_type": "unauthorized-privileged-action"},
        {"finding_id": "M-15", "title": "If FFactory::buyTax and / or FFactory::sellTax is set to 0, buy / sell would revert", "expected_severity": "Medium", "root_cause": "tax calculation does not handle zero buyTax or sellTax values", "bug_class": "denial-of-service", "source_file": "contracts/tax/BondingTax.sol", "affected_contract": "BondingTax", "affected_function": "swapForAsset", "affected_asset": "buy and sell operations", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-16", "title": "Elo calculation error", "expected_severity": "Medium", "root_cause": "Elo calculation uses incorrect math for battle outcome updates", "bug_class": "accounting-desync", "source_file": "contracts/virtualPersona/EloCalculator.sol", "affected_contract": "EloCalculator", "affected_function": "battleElo", "affected_asset": "Elo scores and rewards", "impact_type": "stolen-funds-or-unauthorized-privileged-action"},
        {"finding_id": "M-17", "title": "VirtualGenesisDAO.sol:earlyExecute() proposals can be executed two times", "expected_severity": "Medium", "root_cause": "earlyExecute does not consume or guard proposal execution state consistently", "bug_class": "incomplete-path", "source_file": "contracts/governance/VirtualGenesisDAO.sol", "affected_contract": "VirtualGenesisDAO", "affected_function": "earlyExecute", "affected_asset": "governance execution", "impact_type": "unauthorized-privileged-action"},
        {"finding_id": "M-18", "title": "Genesis.sol:onGenesisSuccess() users may lose their unclaimed agentTokens if a second launch occurs before they’ve claimed their rewards from the first", "expected_severity": "Medium", "root_cause": "second genesis success overwrites or invalidates unclaimed reward state", "bug_class": "accounting-desync", "source_file": "contracts/genesis/Genesis.sol", "affected_contract": "Genesis", "affected_function": "onGenesisSuccess", "affected_asset": "unclaimed agent tokens", "impact_type": "stolen-funds-or-frozen-funds"},
        {"finding_id": "M-19", "title": "Lack of maturity check for non-founder users allowing immediate withdrawals", "expected_severity": "Medium", "root_cause": "withdrawal path omits maturity check for non-founder users", "bug_class": "access-control", "source_file": "contracts/virtualPersona/AgentVeToken.sol", "affected_contract": "AgentVeToken", "affected_function": "withdraw", "affected_asset": "locked stake and rewards", "impact_type": "stolen-funds"},
        {"finding_id": "M-20", "title": "Delegation not revoked on withdrawal allows reward and voting power inflation post-maturity", "expected_severity": "Medium", "root_cause": "withdraw leaves delegation state active after stake exits", "bug_class": "accounting-desync", "source_file": "contracts/virtualPersona/AgentVeToken.sol", "affected_contract": "AgentVeToken", "affected_function": "withdraw", "affected_asset": "delegated voting power and rewards", "impact_type": "stolen-funds-or-inflation"},
        {"finding_id": "M-21", "title": "battleElo is at risk of underflow revert, which may DOS voting", "expected_severity": "Medium", "root_cause": "battleElo arithmetic can underflow for some vote outcomes", "bug_class": "arithmetic", "source_file": "contracts/virtualPersona/EloCalculator.sol", "affected_contract": "EloCalculator", "affected_function": "battleElo", "affected_asset": "voting and Elo updates", "impact_type": "frozen-funds-or-availability"},
        {"finding_id": "M-22", "title": "Founder has to double-stake during migration with the initial LP locked in the old veToken", "expected_severity": "Medium", "root_cause": "migration path requires new stake without releasing or migrating old veToken LP", "bug_class": "incomplete-path", "source_file": "contracts/virtualPersona/AgentMigrator.sol", "affected_contract": "AgentMigrator", "affected_function": "migrate", "affected_asset": "founder LP stake", "impact_type": "frozen-funds"},
        {"finding_id": "M-23", "title": "Using AgentFactory::setAssetToken will lead to loss of funds", "expected_severity": "Medium", "root_cause": "setAssetToken changes the asset boundary without safely migrating or validating dependent balances", "bug_class": "incomplete-upgrade-path", "source_file": "contracts/virtualPersona/AgentFactory.sol", "affected_contract": "AgentFactory", "affected_function": "setAssetToken", "affected_asset": "factory asset token funds", "impact_type": "stolen-funds-or-frozen-funds"},
        {"finding_id": "M-24", "title": "Precision loss in priceALast and priceBLast", "expected_severity": "Medium", "root_cause": "price accumulator fields lose precision during reserve updates", "bug_class": "rounding-accounting", "source_file": "contracts/fun/FPair.sol", "affected_contract": "FPair", "affected_function": "_update", "affected_asset": "pair pricing and accounting", "impact_type": "stolen-funds-or-bad-pricing"},
        {"finding_id": "M-25", "title": "Incorrect mathematical logic", "expected_severity": "Medium", "root_cause": "Elo library uses incorrect mathematical formula", "bug_class": "arithmetic", "source_file": "contracts/libs/Elo.sol", "affected_contract": "Elo", "affected_function": "battleElo", "affected_asset": "Elo scores and rewards", "impact_type": "stolen-funds-or-unauthorized-privileged-action"},
        {"finding_id": "M-26", "title": "Imprecise calculations in launchFor() lead to less liquidity be added to the pair via the router", "expected_severity": "Medium", "root_cause": "launchFor performs imprecise liquidity math before router liquidity addition", "bug_class": "rounding-accounting", "source_file": "contracts/fun/Bonding.sol", "affected_contract": "Bonding", "affected_function": "launchFor", "affected_asset": "pair liquidity and launched tokens", "impact_type": "stolen-funds-or-user-loss"},
    ],
}


def expected_case_items_for_split(split: str) -> list[tuple[str, list[dict[str, Any]]]]:
    if split == "fresh-v6":
        return [(case_id, findings) for case_id, findings in FRESH_EXPECTED.items() if case_id.startswith("contest_400")]
    if split == "fresh-confirmation":
        return [(case_id, findings) for case_id, findings in FRESH_EXPECTED.items() if case_id.startswith("contest_300")]
    return [(case_id, findings) for case_id, findings in FRESH_EXPECTED.items() if not case_id.startswith("contest_300") and not case_id.startswith("contest_400")]


def expected_for_case(case_id: str) -> list[dict[str, Any]]:
    return [dict(row, case_id=case_id) for row in FRESH_EXPECTED.get(case_id, [])]


def write_expected_files(root: Path = PUBLIC_ROOT, *, split: str = "fresh-holdout") -> dict[str, Any]:
    out_dir = root / "expected_findings" / split
    out_dir.mkdir(parents=True, exist_ok=True)
    rows = []
    for case_id, findings in expected_case_items_for_split(split):
        payload = {
            "case_id": case_id,
            "split": split,
            "expected_extracted_after_freeze": True,
            "answer_key_material": True,
            "counts_toward_future_readiness": False,
            "expected_finding_count": len(findings),
            "all_expected_findings": expected_for_case(case_id),
        }
        path = out_dir / f"{case_id}.json"
        path.write_text(json.dumps(payload, indent=2) + "\n")
        rows.append({"case_id": case_id, "expected_finding_count": len(findings), "path": path.relative_to(root).as_posix()})
    return {"status": "PASS", "split": split, "case_count": len(rows), "expected_finding_count": sum(r["expected_finding_count"] for r in rows), "cases": rows}


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Write post-freeze expected finding JSON for fresh holdouts")
    p.add_argument("--root", default=str(PUBLIC_ROOT))
    p.add_argument("--split", default="fresh-holdout")
    p.add_argument("--frozen-only", action="store_true")
    args = p.parse_args(argv)
    result = write_expected_files(Path(args.root), split=args.split)
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
